### ISSUE TITLE
[Bug] Tab bar not shown with "Prefer tabs when opening documents" setting 

### ISSUE THREAD

**Issue by dkocher** [anosidium/Oliphaunt-Feedback-And-Support#11]
### Operating System

14.2.1 (23C71)

### App Version

1.0

### Build Number

4

### Reproduction Steps

1. Select _System Settings… → Desktop & Dock → Prefer tabs when opening documents → Always_
2. Choose _Oliphaunt → New Main Window_
3. No second tab is visible
4. Choose _File → Close Tab (⌘-W)_
5. Tab bar is now visible

### Expected Behaviour

Tab bar should be visible initially after opening new main window.

**Comment by anosidium** [comment]
The next TestFlight build will have this fixed.

**Comment by dkocher** [comment]
Fixed in Version 1.0 (5).
