### ISSUE TITLE
[Bug] Clicking on boosted post opens empty boost, not original post

### ISSUE THREAD

**Issue by nkizz** [anosidium/Oliphaunt-Feedback-And-Support#19]
### Operating System

macOS 14.0 Sonoma

### App Version

1.0

### Build Number

5

### Reproduction Steps

See boosted post in timeline
Double click it to view it in a pop-out window

### Expected Behaviour

The original boosted post opens

### Screenshots

<img width="791" alt="image" src="https://github.com/anosidium/Oliphaunt-Feedback-And-Support/assets/12008806/8d4fb8e3-1d65-4538-a0d9-63231ee232b8">

### Additional Context

I believe this is because boosts are just posts that link out to the other post, and it's opening that post instead of the original

**Comment by anosidium** [comment]
Thanks! I have fixed this and it will be available in the next build.

**Comment by anosidium** [comment]
Fixed in Version 1.0 (6).
