### ISSUE TITLE
[Bug] Popup menu to switch account does not close after selecting item

### ISSUE THREAD

**Issue by dkocher** [anosidium/Oliphaunt-Feedback-And-Support#20]
### Operating System

14.3.1 (23D60)

### App Version

1.0

### Build Number

6

### Reproduction Steps

Select an account in the menu popover from the main window.

### Expected Behaviour

Popover closes after selecting item.

**Comment by anosidium** [comment]
Are you talking about switching account from the sidebar? The bottom part?

**Comment by dkocher** [comment]
> Are you talking about switching account from the sidebar? The bottom part?

Right.

**Comment by anosidium** [comment]
Available in Version 1.0 (15).
