### ISSUE TITLE
[Feature Request] Allow to switch images using arrow keys

### ISSUE THREAD

**Issue by dkocher** [anosidium/Oliphaunt-Feedback-And-Support#22]
### Description

In the image detail view allow to switch multiple items using left and right arrow keys.
![Screenshot 2024-02-26 at 13 47 51](https://github.com/anosidium/Oliphaunt-Feedback-And-Support/assets/71733/3c9d83e8-1c7c-4e38-a863-583160a7663c)

**Comment by anosidium** [comment]
Available in Version 1.0 (15).
