### ISSUE TITLE
[Bug] Text input in toot window with invalid kerning after inserting emoji

### ISSUE THREAD

**Issue by dkocher** [anosidium/Oliphaunt-Feedback-And-Support#5]
### Operating System

14.2.1 (23C71)

### App Version

1.0

### Build Number

4

### Reproduction Steps

![Screenshot 2024-01-11 at 14 20 53](https://github.com/anosidium/Oliphaunt-Feedback-And-Support/assets/71733/06f51b69-b433-4829-94aa-3c15f234cd1a)

### Expected Behaviour

Keep regular font kerning.

**Comment by anosidium** [comment]
Thanks for the bug report, I believe this bug is similar to this report, [Post editor doesn't let you insert text in between](https://github.com/anosidium/Oliphaunt-Feedback-And-Support/issues/1). This will be fixed in the next build.

**Comment by dkocher** [comment]
Fixed in Version 1.0 (5).
